// (c) Copyright 2012 Felipe Magno de Almeida
//
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#ifndef JVB_ADAPT_CLASS_MODIFIERS_HPP
#define JVB_ADAPT_CLASS_MODIFIERS_HPP

#define JVB_ADAPT_CLASS_HAS_STATIC_CHOOSE_static 1
#define JVB_ADAPT_CLASS_HAS_STATIC_CHOOSE_final

#define JVB_ADAPT_CLASS_HAS_STATIC_PRED(S, DATA, M)   \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_HAS_STATIC_CHOOSE_, M)

#define JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_0(M) \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_HAS_STATIC_CHOOSE_, M) JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_1
#define JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_1(M) \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_HAS_STATIC_CHOOSE_, M) JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_0
#define JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_0_END
#define JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_1_END

#define JVB_ADAPT_CLASS_HAS_STATIC(MODIFIERS)   \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_HAS_STATIC_ITERATE_0 MODIFIERS, _END)

#define JVB_ADAPT_CLASS_ATTRIBUTE_DEF_CONSUME_IF_NIL_nil

#endif
