// (c) Copyright 2012 Felipe Magno de Almeida
//
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#ifndef JVB_DETAIL_PREPROCESSOR_MODIFIERS_SEQ_HPP
#define JVB_DETAIL_PREPROCESSOR_MODIFIERS_SEQ_HPP

#include <jvb/detail/modifier_types.hpp>

#include <boost/mpl/vector.hpp>
#include <boost/preprocessor/seq/enum.hpp>

#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD4_static  (static) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3_static  (static) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2_static  (static) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1_static  (static) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD0 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD4_final  (final) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3_final  (final) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2_final  (final) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1_final  (final) \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD0 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD4_nil      \
  JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3 (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3_END      \
  BOOST_PP_EMPTY (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2_END      \
  BOOST_PP_EMPTY (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1_END      \
  BOOST_PP_EMPTY (
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD0_END      \
  BOOST_PP_EMPTY (
  
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3(MODIFIERS)               \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD3_, MODIFIERS) )
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2(MODIFIERS)               \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD2_, MODIFIERS) )
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1(MODIFIERS)               \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD1_, MODIFIERS) )
#define JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD0(MODIFIERS)               \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD0_, MODIFIERS) )

#define JVB_ADAPT_CLASS_MODIFIERS_SEQ(MODIFIERS)                        \
  BOOST_PP_CAT(JVB_ADAPT_CLASS_MODIFIERS_SEQ_KEYWORD4_, MODIFIERS END) )

#endif
